package view;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import controller.QuizQuestaoController;
import model.dao.QuizQuestaoDAO;
import model.dao.QuizDAO;
import model.vo.QuizQuestaoVO;

public class AlterarQuestao extends javax.swing.JFrame {

	/**
	 * Creates new form AllterarQuestão
	 */
	String autor = null;
	DefaultTableModel model = new DefaultTableModel();
	public AlterarQuestao(String autor) {
		this.autor = autor;
		initComponents();
		setExtendedState(MAXIMIZED_BOTH);
	}
 
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		txtIdQuestao = new javax.swing.JTextField();
		bttnPesquisarIdQuiz = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		txtIdQuiz = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		bttnVoltar = new javax.swing.JButton();
		bttnQuizCompleto = new javax.swing.JButton();
		bttnPesquisarQuestão = new javax.swing.JButton();
		bttnExcluirQuiz = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setForeground(new java.awt.Color(255, 255, 255));

		jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		jLabel1.setText("Informe o id do quiz para ver as questões:");

		txtIdQuestao.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtIdQuestaoActionPerformed(evt);
			}
		});

		bttnPesquisarIdQuiz.setBackground(new java.awt.Color(103, 126, 119));
		bttnPesquisarIdQuiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/search.png"))); // NOI18N
		bttnPesquisarIdQuiz.setBorder(null);
		bttnPesquisarIdQuiz.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bttnPesquisarIdQuizActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(107, 131, 125));
		jLabel2.setText("Jogos salvos");

		
		model.addColumn("ID");
		model.addColumn("Pergunta");
		model.addColumn("Alternativa 1");
		model.addColumn("Alternativa 2");
		model.addColumn("Alternativa 3");
		model.addColumn("Alternativa 4");

		jTable1.setModel(model);
		// jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);

		TableColumn colunaID = jTable1.getColumnModel().getColumn(0);
		colunaID.setPreferredWidth(40);
		TableColumn colunaPergunta = jTable1.getColumnModel().getColumn(1);
		colunaPergunta.setPreferredWidth(465);
		TableColumn colunaAlternativa1 = jTable1.getColumnModel().getColumn(2);
		colunaAlternativa1.setPreferredWidth(110);
		TableColumn colunaAlternativa2 = jTable1.getColumnModel().getColumn(3);
		colunaAlternativa2.setPreferredWidth(110);
		TableColumn colunaAlternativa3 = jTable1.getColumnModel().getColumn(4);
		colunaAlternativa3.setPreferredWidth(110);
		TableColumn colunaAlternativa4 = jTable1.getColumnModel().getColumn(5);
		colunaAlternativa4.setPreferredWidth(110);

		jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);

		jTable1.setRowHeight(50);

		jScrollPane1.setViewportView(jTable1);
		if (jTable1.getColumnModel().getColumnCount() > 0) {
			jTable1.getColumnModel().getColumn(0).setHeaderValue("ID");
			jTable1.getColumnModel().getColumn(1).setHeaderValue("Pergunta");
			jTable1.getColumnModel().getColumn(2).setHeaderValue("Alternativa 1");
			jTable1.getColumnModel().getColumn(3).setHeaderValue("Alternativa 2");
			jTable1.getColumnModel().getColumn(4).setHeaderValue("Alternativa 3");
			jTable1.getColumnModel().getColumn(5).setHeaderValue("Alternativa 4");
		}

		jTable1.setColumnSelectionAllowed(true);
		jScrollPane1.setViewportView(jTable1);
		jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jTable1.setColumnSelectionAllowed(true);
		jScrollPane1.setViewportView(jTable1);
		jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

		txtIdQuiz.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtIdQuizActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		jLabel3.setText("Informe o número da questão que deseja consultar:");

		bttnVoltar.setBackground(new java.awt.Color(105, 129, 122));
		bttnVoltar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
		bttnVoltar.setForeground(new java.awt.Color(255, 255, 255));
		bttnVoltar.setText("Voltar");
		bttnVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bttnVoltarActionPerformed(evt);
			}
		});

		bttnQuizCompleto.setBackground(new java.awt.Color(105, 129, 122));
		bttnQuizCompleto.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
		bttnQuizCompleto.setForeground(new java.awt.Color(255, 255, 255));
		bttnQuizCompleto.setText("Quiz completo");
		bttnQuizCompleto.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bttnQuizCompletoActionPerformed(evt);
			}
		});

		bttnPesquisarQuestão.setBackground(new java.awt.Color(103, 126, 119));
		bttnPesquisarQuestão.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/search.png"))); // NOI18N
		bttnPesquisarQuestão.setBorder(null);
		bttnPesquisarQuestão.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				 bttnPesquisarQuestãoActionPerformed(evt);
			}
		});

		bttnExcluirQuiz.setBackground(new java.awt.Color(103, 126, 119));
		bttnExcluirQuiz.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
		bttnExcluirQuiz.setForeground(new java.awt.Color(255, 255, 255));
		bttnExcluirQuiz.setText("Excluir Quiz");
		bttnExcluirQuiz.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bttnExcluirQuizActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel2)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(292, 292, 292).addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(txtIdQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 373,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(bttnPesquisarIdQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41,
										Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(txtIdQuestao, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 420,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(bttnPesquisarQuestão, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(jScrollPane1)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(bttnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 171,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(209, 209, 209)
								.addComponent(bttnQuizCompleto, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGap(201, 201, 201).addComponent(bttnExcluirQuiz,
										javax.swing.GroupLayout.PREFERRED_SIZE, 178,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(293, 293, 293)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(52, 52, 52).addComponent(jLabel2)
						.addGap(32, 32, 32)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(txtIdQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(bttnPesquisarIdQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtIdQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(bttnPesquisarQuestão, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(27, 27, 27)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(bttnExcluirQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, 50,
												Short.MAX_VALUE)
										.addGap(54, 54, 54))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(bttnVoltar, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(bttnQuizCompleto, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGap(53, 53, 53)))));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	private void txtIdQuestaoActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void bttnPesquisarIdQuizActionPerformed(java.awt.event.ActionEvent evt) {
		// Defina o número de linhas no modelo da tabela

		String idQuiz = txtIdQuiz.getText(); // Obter o texto do JTextField
		if (idQuiz != null && !idQuiz.isEmpty()) {
			List<QuizQuestaoVO> questoes = new QuizQuestaoDAO().consultarQuestoes(idQuiz);
			model.setRowCount(new QuizDAO().totalDeQuestoesQuiz(idQuiz));

			int rowCount = questoes.size();
			model.setRowCount(rowCount);
			for (int i = 0; i < rowCount; i++) {
				QuizQuestaoVO q = questoes.get(i);
				model.setValueAt(q.getId(), i, 0); // Defina o valor da coluna 0 com o ID da questão
				model.setValueAt(q.getPergunta(), i, 1); // Defina o valor da coluna 1 com a pergunta
				model.setValueAt(q.getAlternativaA(), i, 2); // Defina o valor da coluna 2 com a alternativa 1
				model.setValueAt(q.getAlternativaB(), i, 3); // Defina o valor da coluna 3 com a alternativa 2
				model.setValueAt(q.getAlternativaC(), i, 4); // Defina o valor da coluna 4 com a alternativa 3
				model.setValueAt(q.getAlternativaD(), i, 5); // Defina o valor da coluna 5 com a alternativa 4
			}
		} else {
			JOptionPane.showMessageDialog(null, "O TextField está vazio.");
		}
	}

	private void txtIdQuizActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}
	final AlterarQuestao tela1 = this;
	private void bttnVoltarActionPerformed(java.awt.event.ActionEvent evt) {
		TelaDeMenu tela = new TelaDeMenu();
		tela.getLblNomeProfessor().setText(autor);
		tela.setVisible(true);
		tela1.dispose();
	}

	private void bttnPesquisarQuestãoActionPerformed(java.awt.event.ActionEvent evt) {
		int idPergunta = Integer.valueOf(txtIdQuestao.getText());
		new QuizQuestaoController().consultarQuestaoId(idPergunta, autor);
		tela1.dispose();
	}

	private void bttnExcluirQuizActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String texto = txtIdQuiz.getText();
		new QuizDAO().excluirQuiz(texto);
	}

	private void bttnQuizCompletoActionPerformed(java.awt.event.ActionEvent evt) {
		//int idPergunta = Integer.valueOf(txtIdQuestao.getText());
		new QuizQuestaoController().consultarQuestaoId(1, null);
		tela1.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AlterarQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AlterarQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AlterarQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AlterarQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AlterarQuestao(null).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton bttnExcluirQuiz;
	private javax.swing.JButton bttnPesquisarIdQuiz;
	private javax.swing.JButton bttnPesquisarQuestão;
	private javax.swing.JButton bttnQuizCompleto;
	private javax.swing.JButton bttnVoltar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField txtIdQuestao;
	private javax.swing.JTextField txtIdQuiz;
	// End of variables declaration
}