package view;

import controller.QuizController;

/**
 *
 * @author Waldir Neto
 */public class CriarQuiz extends javax.swing.JFrame {

	    /**
	     * Creates new form CriarQuiz
	     */
	 	String autor;
	    public CriarQuiz(String autor) {
	        initComponents();
	        this.autor = autor;
	        setExtendedState(MAXIMIZED_BOTH);
	    }
 
	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jPanel1 = new javax.swing.JPanel();
	        jLabel2 = new javax.swing.JLabel();
	        jLabel3 = new javax.swing.JLabel();
	        jLabel4 = new javax.swing.JLabel();
	        QuizTitulojTextField1 = new javax.swing.JTextField();
	        jLabel5 = new javax.swing.JLabel();
	        TempoParaResponderQuizjComboBox1 = new javax.swing.JComboBox<>();
	        ContinuarjButton1 = new javax.swing.JButton();
	        bttnVoltar = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

	        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 26.png"))); // NOI18N

	        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 76)); // NOI18N
	        jLabel3.setForeground(new java.awt.Color(107, 131, 125));
	        jLabel3.setText("Criar Quiz!");

	        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
	        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
	        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
	        jLabel4.setText("Título do quiz:");

	        QuizTitulojTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
	        QuizTitulojTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

	        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
	        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
	        jLabel5.setText("Tempo para responder o quiz:");

	        TempoParaResponderQuizjComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
	        TempoParaResponderQuizjComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 minutos", "30 minutos", "1 hora", "2 horas" }));
	        TempoParaResponderQuizjComboBox1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
	        TempoParaResponderQuizjComboBox1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                TempoParaResponderQuizjComboBox1ActionPerformed(evt);
	            }
	        });

	        ContinuarjButton1.setBackground(new java.awt.Color(107, 131, 125));
	        ContinuarjButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
	        ContinuarjButton1.setForeground(new java.awt.Color(255, 255, 255));
	        ContinuarjButton1.setText("Continuar");
	        ContinuarjButton1.setBorder(null);
	        ContinuarjButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                ContinuarjButton1ActionPerformed(evt);
	            }
	        });

	        bttnVoltar.setBackground(new java.awt.Color(107, 131, 125));
	        bttnVoltar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
	        bttnVoltar.setForeground(new java.awt.Color(255, 255, 255));
	        bttnVoltar.setText("Voltar");
	        bttnVoltar.setBorder(null);
	        bttnVoltar.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                bttnVoltarActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1.setLayout(jPanel1Layout);
	        jPanel1Layout.setHorizontalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addGap(129, 129, 129)
	                .addComponent(jLabel2)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel1Layout.createSequentialGroup()
	                        .addGap(264, 264, 264)
	                        .addComponent(jLabel3))
	                    .addGroup(jPanel1Layout.createSequentialGroup()
	                        .addGap(425, 425, 425)
	                        .addComponent(TempoParaResponderQuizjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addGroup(jPanel1Layout.createSequentialGroup()
	                        .addGap(385, 385, 385)
	                        .addComponent(jLabel5))
	                    .addGroup(jPanel1Layout.createSequentialGroup()
	                        .addGap(133, 133, 133)
	                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addGroup(jPanel1Layout.createSequentialGroup()
	                                .addComponent(bttnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(ContinuarjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
	                            .addComponent(jLabel4)
	                            .addComponent(QuizTitulojTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))))
	                .addContainerGap(320, Short.MAX_VALUE))
	        );
	        jPanel1Layout.setVerticalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addGap(51, 51, 51)
	                .addComponent(jLabel3)
	                .addGap(100, 100, 100)
	                .addComponent(jLabel4)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addComponent(QuizTitulojTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jLabel5)
	                .addGap(18, 18, 18)
	                .addComponent(TempoParaResponderQuizjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(ContinuarjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(bttnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(116, 116, 116))
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addComponent(jLabel2)
	                .addGap(0, 252, Short.MAX_VALUE))
	        );

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        );

	        pack();
	    }// </editor-fold>                        

	    private void TempoParaResponderQuizjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                                                 
	        // TODO add your handling code here:
	    }                                                                

	    private void ContinuarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                                  
	        String nomeQuiz = QuizTitulojTextField1.getText();
	        int i = TempoParaResponderQuizjComboBox1.getSelectedIndex();
	        String tempoQuiz = TempoParaResponderQuizjComboBox1.getItemAt(i);
	       
	        new QuizController().criarQuiz(nomeQuiz, tempoQuiz, autor);
	        tela1.dispose();
	    }                                                 
	    final CriarQuiz tela1 = this;
	    private void bttnVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                           
	        TelaDeMenu tela = new TelaDeMenu();
	        tela.getLblNomeProfessor().setText(autor);
	        tela.setVisible(true); 
	        tela1.dispose();
	    }                                          

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(CriarQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(CriarQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(CriarQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(CriarQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new CriarQuiz(null).setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton ContinuarjButton1;
	    private javax.swing.JTextField QuizTitulojTextField1;
	    private javax.swing.JComboBox<String> TempoParaResponderQuizjComboBox1;
	    private javax.swing.JButton bttnVoltar;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JPanel jPanel1;
	    // End of variables declaration                   
	}
