package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import application.Main;
import controller.FlashCardController;
import javafx.application.Platform;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;

public class FlashCardCriar extends javax.swing.JFrame {

	/**
	 * Creates new form FlashCardCriar
	 */
	String idFlashCard;

	public FlashCardCriar(String idFlashCard) {
		initComponents();
		this.idFlashCard = idFlashCard;
		setExtendedState(JFrame.MAXIMIZED_BOTH);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		imagemjLabel2 = new javax.swing.JLabel();
		jLabelAvisode700char = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		QuestaoProfInserirjEditorPane1 = new javax.swing.JEditorPane();
		FalsojCheckBox1 = new javax.swing.JCheckBox();
		VerdadeirojCheckBox2 = new javax.swing.JCheckBox();
		ProximoCardjButton1 = new javax.swing.JButton();
		FinalizarjButton2 = new javax.swing.JButton();
		jScrollPane3 = new javax.swing.JScrollPane();
		BreveExplicacaojEditorPane2 = new javax.swing.JEditorPane();
		BreveExplicaçãochar1 = new javax.swing.JLabel();

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jPanel3.add(FalsojCheckBox1);
		jPanel3.add(VerdadeirojCheckBox2);
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 1535, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 786, Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(new java.awt.GridLayout());

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));

		imagemjLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Flash Card.png"))); // NOI18N

		jLabelAvisode700char.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
		jLabelAvisode700char.setText("Digite até 700 caracteres");
		jLabelAvisode700char.setName(""); // NOI18N

		QuestaoProfInserirjEditorPane1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
		jScrollPane2.setViewportView(QuestaoProfInserirjEditorPane1);

		FalsojCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		FalsojCheckBox1.setText("Falso");
		FalsojCheckBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				if (FalsojCheckBox1.isSelected()) {
					VerdadeirojCheckBox2.setSelected(false);
				}
			}
		});

		VerdadeirojCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		VerdadeirojCheckBox2.setText("Verdadeiro");
		VerdadeirojCheckBox2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (VerdadeirojCheckBox2.isSelected()) {
					FalsojCheckBox1.setSelected(false);
				}

			}
		});

		ProximoCardjButton1.setBackground(new java.awt.Color(247, 247, 142));
		ProximoCardjButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		ProximoCardjButton1.setText("Próximo card");
		ProximoCardjButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		ProximoCardjButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ProximoCardjButton1ActionPerformed(evt);
			}
		});

		FinalizarjButton2.setBackground(new java.awt.Color(247, 247, 142));
		FinalizarjButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		FinalizarjButton2.setText("Finalizar");
		FinalizarjButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		FinalizarjButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				FinalizarjButton2ActionPerformed(evt);
			}
		});

		BreveExplicacaojEditorPane2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
		jScrollPane3.setViewportView(BreveExplicacaojEditorPane2);

		BreveExplicaçãochar1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
		BreveExplicaçãochar1.setText("Dê uma breve explicação:");
		BreveExplicaçãochar1.setName(""); // NOI18N

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel3Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
										.addComponent(ProximoCardjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(FinalizarjButton2,
												javax.swing.GroupLayout.PREFERRED_SIZE, 112,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(380, 380, 380))
						.addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1081,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel3Layout.createSequentialGroup().addGap(84, 84, 84)
												.addComponent(imagemjLabel2))
										.addGroup(jPanel3Layout.createSequentialGroup().addGap(152, 152, 152)
												.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
														1080, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel3Layout.createSequentialGroup().addGap(320, 320, 320)
												.addComponent(VerdadeirojCheckBox2).addGap(383, 383, 383)
												.addComponent(FalsojCheckBox1))
										.addGroup(jPanel3Layout.createSequentialGroup().addGap(124, 124, 124)
												.addGroup(jPanel3Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(BreveExplicaçãochar1)
														.addComponent(jLabelAvisode700char)))))
								.addContainerGap(303, Short.MAX_VALUE))
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
										.addComponent(jLabel1).addGap(0, 0, Short.MAX_VALUE))));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(82, 82, 82).addComponent(imagemjLabel2)
						.addGap(63, 63, 63).addComponent(jLabelAvisode700char)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup().addGap(18, 18, 18)
										.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89,
												Short.MAX_VALUE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
										.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(FalsojCheckBox1).addComponent(VerdadeirojCheckBox2))
										.addGap(13, 13, 13)))
						.addComponent(BreveExplicaçãochar1).addGap(18, 18, 18)
						.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(47, 47, 47)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(ProximoCardjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(FinalizarjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(160, 160, 160))
				.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jLabel1).addGap(0, 0, Short.MAX_VALUE))));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel3,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		getContentPane().add(jPanel2);

		pack();
	}// </editor-fold>

	final FlashCardCriar tela = this;

	private void FalsojCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void ProximoCardjButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String frase = QuestaoProfInserirjEditorPane1.getText();
		String explicacao = BreveExplicacaojEditorPane2.getText();
		int condicao = 0;
		if (VerdadeirojCheckBox2.isSelected()) {
			condicao = 1;
		} else if (FalsojCheckBox1.isSelected()) {
			condicao = 0;
		}

		new FlashCardController().adcionarQuestao(idFlashCard, frase, condicao, explicacao, tela);
	}

	private void FinalizarjButton2ActionPerformed(java.awt.event.ActionEvent evt) {

		JOptionPane.showMessageDialog(null, "O codigo do jogo é : " + idFlashCard);
		tela.dispose();
		Platform.runLater(() -> {
			try {
				FXMLLoader loader = new FXMLLoader(getClass().getResource("/view/MenuProfessorView.fxml"));
				Parent parent = loader.load();

				Scene scene = new Scene(parent);

				Main.getStage().setScene(scene);
			} catch (IOException e) {
				e.printStackTrace();
			}
		});
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FlashCardCriar.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FlashCardCriar.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FlashCardCriar.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FlashCardCriar.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FlashCardCriar(null).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JEditorPane BreveExplicacaojEditorPane2;
	private javax.swing.JLabel BreveExplicaçãochar1;
	private javax.swing.JCheckBox FalsojCheckBox1;
	private javax.swing.JButton FinalizarjButton2;
	private javax.swing.JButton ProximoCardjButton1;
	private javax.swing.JEditorPane QuestaoProfInserirjEditorPane1;
	private javax.swing.JCheckBox VerdadeirojCheckBox2;
	private javax.swing.JLabel imagemjLabel2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabelAvisode700char;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;

	// End of variables declaration
	public javax.swing.JEditorPane getBreveExplicacaojEditorPane2() {
		return BreveExplicacaojEditorPane2;
	}

	public void setBreveExplicacaojEditorPane2(javax.swing.JEditorPane breveExplicacaojEditorPane2) {
		BreveExplicacaojEditorPane2 = breveExplicacaojEditorPane2;
	}

	public javax.swing.JCheckBox getFalsojCheckBox1() {
		return FalsojCheckBox1;
	}

	public void setFalsojCheckBox1(javax.swing.JCheckBox falsojCheckBox1) {
		FalsojCheckBox1 = falsojCheckBox1;
	}

	public javax.swing.JEditorPane getQuestaoProfInserirjEditorPane1() {
		return QuestaoProfInserirjEditorPane1;
	}

	public void setQuestaoProfInserirjEditorPane1(javax.swing.JEditorPane questaoProfInserirjEditorPane1) {
		QuestaoProfInserirjEditorPane1 = questaoProfInserirjEditorPane1;
	}

	public javax.swing.JCheckBox getVerdadeirojCheckBox2() {
		return VerdadeirojCheckBox2;
	}

	public void setVerdadeirojCheckBox2(javax.swing.JCheckBox verdadeirojCheckBox2) {
		VerdadeirojCheckBox2 = verdadeirojCheckBox2;
	}

}
