/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import controller.RestaurarSenhaController;

/**
 *
 * @author almei
 */
public class TelaRestaurarSenha extends javax.swing.JFrame {

	/**
	 * Creates new form TelaRestaurarSenha
	 */
	public TelaRestaurarSenha() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		lblCadastre = new javax.swing.JLabel();
		lblNome = new javax.swing.JLabel();
		txtSobrenome = new javax.swing.JTextField();
		lblSobrenome = new javax.swing.JLabel();
		lblConfirmarSenha = new javax.swing.JLabel();
		pfSenha = new javax.swing.JPasswordField();
		lblSenha = new javax.swing.JLabel();
		pfConfirmaSenha = new javax.swing.JPasswordField();
		bttnRedefinir = new javax.swing.JButton();
		lblConfirmarSenha2 = new javax.swing.JLabel();
		lblConfirmarSenha3 = new javax.swing.JLabel();
		txtEmail = new javax.swing.JTextField();
		txtNomeCachorro = new javax.swing.JTextField();
		txtComidaFav = new javax.swing.JTextField();
		txtNome = new javax.swing.JTextField();
		jCheckBox1 = new javax.swing.JCheckBox();
		lblComidaFavorita = new javax.swing.JLabel();
		lblComidaFavorita1 = new javax.swing.JLabel();
		txtDataNasc = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

		jPanel1.setBackground(new java.awt.Color(237, 243, 246));
		jPanel1.setPreferredSize(new java.awt.Dimension(594, 720));

		jPanel2.setBackground(new java.awt.Color(255, 252, 252));
		jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

		lblCadastre.setFont(new java.awt.Font("Segoe UI Black", 0, 40)); // NOI18N
		lblCadastre.setForeground(new java.awt.Color(3, 33, 62));
		lblCadastre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblCadastre.setText("Redefinir senha");

		lblNome.setBackground(new java.awt.Color(3, 33, 62));
		lblNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
		lblNome.setForeground(new java.awt.Color(3, 33, 62));
		lblNome.setText("Nome");

		txtSobrenome.setBackground(new java.awt.Color(241, 237, 237));
		txtSobrenome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		txtSobrenome.setForeground(new java.awt.Color(0, 0, 0));
		txtSobrenome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		txtSobrenome.setAlignmentX(1.0F);
		txtSobrenome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
		txtSobrenome.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtSobrenomeActionPerformed(evt);
			}
		});

		lblSobrenome.setBackground(new java.awt.Color(3, 33, 62));
		lblSobrenome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
		lblSobrenome.setForeground(new java.awt.Color(3, 33, 62));
		lblSobrenome.setText("Sobrenome");

		lblConfirmarSenha.setBackground(new java.awt.Color(3, 33, 62));
		lblConfirmarSenha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
		lblConfirmarSenha.setForeground(new java.awt.Color(3, 33, 62));
		lblConfirmarSenha.setText("Confirmar senha");

		pfSenha.setBackground(new java.awt.Color(242, 237, 237));
		pfSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		pfSenha.setForeground(new java.awt.Color(0, 0, 0));
		pfSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		pfSenha.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pfSenhaActionPerformed(evt);
			}
		});

		lblSenha.setBackground(new java.awt.Color(3, 33, 62));
		lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
		lblSenha.setForeground(new java.awt.Color(3, 33, 62));
		lblSenha.setText("Nova senha");

		pfConfirmaSenha.setBackground(new java.awt.Color(241, 237, 237));
		pfConfirmaSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		pfConfirmaSenha.setForeground(new java.awt.Color(0, 0, 0));
		pfConfirmaSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		pfConfirmaSenha.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pfConfirmaSenhaActionPerformed(evt);
			}
		});

		bttnRedefinir.setBackground(new java.awt.Color(241, 237, 237));
		bttnRedefinir.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
		bttnRedefinir.setForeground(new java.awt.Color(6, 31, 55));
		bttnRedefinir.setText("REDEFINIR");
		bttnRedefinir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bttnRedefinirActionPerformed(evt);
			}
		});

		lblConfirmarSenha2.setBackground(new java.awt.Color(3, 33, 62));
		lblConfirmarSenha2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
		lblConfirmarSenha2.setForeground(new java.awt.Color(3, 33, 62));
		lblConfirmarSenha2.setText("Email");

		lblConfirmarSenha3.setBackground(new java.awt.Color(3, 33, 62));
		lblConfirmarSenha3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
		lblConfirmarSenha3.setForeground(new java.awt.Color(3, 33, 62));
		lblConfirmarSenha3.setText("Nome do pet");

		txtEmail.setBackground(new java.awt.Color(241, 237, 237));
		txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		txtEmail.setForeground(new java.awt.Color(0, 0, 0));
		txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		txtEmail.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtEmailActionPerformed(evt);
			}
		});

		txtNomeCachorro.setBackground(new java.awt.Color(241, 237, 237));
		txtNomeCachorro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		txtNomeCachorro.setForeground(new java.awt.Color(0, 0, 0));
		txtNomeCachorro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		txtNomeCachorro.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtNomeCachorroActionPerformed(evt);
			}
		});

		txtComidaFav.setBackground(new java.awt.Color(241, 237, 237));
		txtComidaFav.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		txtComidaFav.setForeground(new java.awt.Color(0, 0, 0));
		txtComidaFav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		txtComidaFav.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtComidaFavActionPerformed(evt);
			}
		});

		txtNome.setBackground(new java.awt.Color(241, 237, 237));
		txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		txtNome.setForeground(new java.awt.Color(0, 0, 0));
		txtNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		txtNome.setAlignmentX(1.0F);
		txtNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
		txtNome.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtNomeActionPerformed(evt);
			}
		});

		jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jCheckBox1.setForeground(new java.awt.Color(3, 33, 62));
		jCheckBox1.setText("Mostrar senha");
		jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox1ActionPerformed(evt);
			}
		});

		lblComidaFavorita.setBackground(new java.awt.Color(3, 33, 62));
		lblComidaFavorita.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
		lblComidaFavorita.setForeground(new java.awt.Color(3, 33, 62));
		lblComidaFavorita.setText("Comida favorita");

		lblComidaFavorita1.setBackground(new java.awt.Color(3, 33, 62));
		lblComidaFavorita1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
		lblComidaFavorita1.setForeground(new java.awt.Color(3, 33, 62));
		lblComidaFavorita1.setText("Data de Nascimento ");

		txtDataNasc.setBackground(new java.awt.Color(241, 237, 237));
		txtDataNasc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		txtDataNasc.setForeground(new java.awt.Color(0, 0, 0));
		txtDataNasc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		txtDataNasc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtDataNascActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup()
								.addComponent(lblCadastre, javax.swing.GroupLayout.PREFERRED_SIZE, 481,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(163, 163, 163)
						.addComponent(bttnRedefinir, javax.swing.GroupLayout.PREFERRED_SIZE, 141,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 168,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(txtNomeCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, 184,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jCheckBox1).addComponent(lblComidaFavorita)
								.addGroup(jPanel2Layout.createSequentialGroup().addGroup(
										jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 173,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(lblSenha))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(lblConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE,
														119, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(pfConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE,
														179, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addGroup(jPanel2Layout.createSequentialGroup().addComponent(lblComidaFavorita1)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(lblConfirmarSenha3,
														javax.swing.GroupLayout.PREFERRED_SIZE, 178,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(txtComidaFav, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 358,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(lblConfirmarSenha2,
														javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel2Layout.createSequentialGroup()
																.addComponent(txtNome,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 168,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel2Layout.createSequentialGroup()
																		.addComponent(lblNome).addGap(131, 131, 131)))
														.addGroup(jPanel2Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(lblSobrenome,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 119,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(txtSobrenome,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 184,
																		javax.swing.GroupLayout.PREFERRED_SIZE))))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap(12, Short.MAX_VALUE)
						.addComponent(lblCadastre, javax.swing.GroupLayout.PREFERRED_SIZE, 98,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblNome).addComponent(lblSobrenome))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(lblConfirmarSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 17,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(lblComidaFavorita)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(txtComidaFav, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(14, 14, 14)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblComidaFavorita1).addComponent(lblConfirmarSenha3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtNomeCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblSenha).addComponent(lblConfirmarSenha,
										javax.swing.GroupLayout.PREFERRED_SIZE, 22,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(pfConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(bttnRedefinir, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(31, 31, 31)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap(55, Short.MAX_VALUE)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(56, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup().addContainerGap(46, Short.MAX_VALUE)
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(60, Short.MAX_VALUE)));

		getContentPane().add(jPanel1);
		final TelaRestaurarSenha tela = this;
		bttnRedefinir.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				String nome = txtNome.getText();
				String sobrenome = txtSobrenome.getText();
				String teste_data = txtDataNasc.getText();
				String nomeCachorro = txtNomeCachorro.getText();
				String comidaFav = txtComidaFav.getText();
				String senha = new String(pfSenha.getPassword());
				String confirmarSenha = new String(pfConfirmaSenha.getPassword());
				String email = txtEmail.getText();
				new RestaurarSenhaController().restaurarSenha(nome, sobrenome, email, senha, confirmarSenha, teste_data,
						nomeCachorro, comidaFav, tela);
			}
		});

		setSize(new java.awt.Dimension(608, 727));
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void txtSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void pfSenhaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void pfConfirmaSenhaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void bttnRedefinirActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void txtNomeCachorroActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void txtComidaFavActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jCheckBox1.isSelected()) {
			pfSenha.setEchoChar((char) 0);
			pfConfirmaSenha.setEchoChar((char) 0);
		} else {
			pfSenha.setEchoChar('*');
			pfConfirmaSenha.setEchoChar('*');
		}
	}

	private void txtDataNascActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaRestaurarSenha.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaRestaurarSenha.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaRestaurarSenha.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaRestaurarSenha.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaRestaurarSenha().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton bttnRedefinir;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JLabel lblCadastre;
	private javax.swing.JLabel lblComidaFavorita;
	private javax.swing.JLabel lblComidaFavorita1;
	private javax.swing.JLabel lblConfirmarSenha;
	private javax.swing.JLabel lblConfirmarSenha2;
	private javax.swing.JLabel lblConfirmarSenha3;
	private javax.swing.JLabel lblNome;
	private javax.swing.JLabel lblSenha;
	private javax.swing.JLabel lblSobrenome;
	private javax.swing.JPasswordField pfConfirmaSenha;
	private javax.swing.JPasswordField pfSenha;
	private javax.swing.JTextField txtComidaFav;
	private javax.swing.JTextField txtDataNasc;
	private javax.swing.JTextField txtEmail;
	private javax.swing.JTextField txtNome;
	private javax.swing.JTextField txtNomeCachorro;
	private javax.swing.JTextField txtSobrenome;
	// End of variables declaration
}
