/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;

import controller.CadastroController;

/**
 *
 * @author almei
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCadastre = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtSobrenome = new javax.swing.JTextField();
        lblSobrenome = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField(); 
        lblEmail = new javax.swing.JLabel();
        lblConfirmarSenha = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        lblSenha = new javax.swing.JLabel();
        pfConfirmaSenha = new javax.swing.JPasswordField();
        checkBoxProfessor = new javax.swing.JCheckBox();
        checkBoxAluno = new javax.swing.JCheckBox();
        bttnCadastrar = new javax.swing.JButton();
        lblConfirmarSenha1 = new javax.swing.JLabel();
        lblConfirmarSenha2 = new javax.swing.JLabel();
        lblConfirmarSenha3 = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JTextField();
        txtNomeCachorro = new javax.swing.JTextField();
        txtNomeUser = new javax.swing.JTextField();
        lblEmail1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtComidaFavorita = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBackground(new java.awt.Color(237, 243, 246));
        jPanel1.setPreferredSize(new java.awt.Dimension(594, 720));

        jPanel2.setBackground(new java.awt.Color(255, 252, 252));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lblCadastre.setFont(new java.awt.Font("Segoe UI Black", 0, 40)); // NOI18N
        lblCadastre.setForeground(new java.awt.Color(3, 33, 62));
        lblCadastre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastre.setText("Cadastrar-se");

        lblNome.setBackground(new java.awt.Color(3, 33, 62));
        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNome.setForeground(new java.awt.Color(3, 33, 62));
        lblNome.setText("Nome");

        txtSobrenome.setBackground(new java.awt.Color(241, 237, 237));
        txtSobrenome.setForeground(new java.awt.Color(0, 0, 0));
        txtSobrenome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSobrenome.setAlignmentX(1.0F);
        txtSobrenome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSobrenomeActionPerformed(evt);
            }
        });

        lblSobrenome.setBackground(new java.awt.Color(3, 33, 62));
        lblSobrenome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSobrenome.setForeground(new java.awt.Color(3, 33, 62));
        lblSobrenome.setText("Sobrenome");

        txtEmail.setBackground(new java.awt.Color(241, 237, 237));
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblEmail.setBackground(new java.awt.Color(3, 33, 62));
        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(3, 33, 62));
        lblEmail.setText("Email");

        lblConfirmarSenha.setBackground(new java.awt.Color(3, 33, 62));
        lblConfirmarSenha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblConfirmarSenha.setForeground(new java.awt.Color(3, 33, 62));
        lblConfirmarSenha.setText("Confirmar senha");

        pfSenha.setBackground(new java.awt.Color(242, 237, 237));
        pfSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfSenhaActionPerformed(evt);
            }
        });

        lblSenha.setBackground(new java.awt.Color(3, 33, 62));
        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(3, 33, 62));
        lblSenha.setText("Senha");

        pfConfirmaSenha.setBackground(new java.awt.Color(241, 237, 237));
        pfConfirmaSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pfConfirmaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfConfirmaSenhaActionPerformed(evt);
            }
        });

        checkBoxProfessor.setBackground(new java.awt.Color(255, 255, 255));
        checkBoxProfessor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkBoxProfessor.setForeground(new java.awt.Color(3, 31, 58));
        checkBoxProfessor.setText("Sou professor");
        checkBoxProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(checkBoxProfessor.isSelected()) {
                	checkBoxAluno.setSelected(false);
                }
            }
        });

        checkBoxAluno.setBackground(new java.awt.Color(255, 255, 255));
        checkBoxAluno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkBoxAluno.setForeground(new java.awt.Color(3, 31, 58));
        checkBoxAluno.setText("Sou aluno");
        checkBoxAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	if(checkBoxAluno.isSelected()) {
                	checkBoxProfessor.setSelected(false);
                }
            }
        });

        bttnCadastrar.setBackground(new java.awt.Color(241, 237, 237));
        bttnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bttnCadastrar.setForeground(new java.awt.Color(6, 31, 55));
        bttnCadastrar.setText("CADASTRAR");
        

        lblConfirmarSenha1.setBackground(new java.awt.Color(3, 33, 62));
        lblConfirmarSenha1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblConfirmarSenha1.setForeground(new java.awt.Color(0, 0, 0));
        lblConfirmarSenha1.setText("Dados para redefinir senha");

        lblConfirmarSenha2.setBackground(new java.awt.Color(3, 33, 62));
        lblConfirmarSenha2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblConfirmarSenha2.setForeground(new java.awt.Color(3, 33, 62));
        lblConfirmarSenha2.setText("Data de Nascimento ");

        lblConfirmarSenha3.setBackground(new java.awt.Color(3, 33, 62));
        lblConfirmarSenha3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblConfirmarSenha3.setForeground(new java.awt.Color(3, 33, 62));
        lblConfirmarSenha3.setText("Nome do pet");

        txtDataNasc.setBackground(new java.awt.Color(241, 237, 237));
        txtDataNasc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascActionPerformed(evt);
            }
        });

        txtNomeCachorro.setBackground(new java.awt.Color(241, 237, 237));
        txtNomeCachorro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNomeCachorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCachorroActionPerformed(evt);
            }
        });

        txtNomeUser.setBackground(new java.awt.Color(241, 237, 237));
        txtNomeUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNomeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeUserActionPerformed(evt);
            }
        });

        lblEmail1.setBackground(new java.awt.Color(3, 33, 62));
        lblEmail1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmail1.setForeground(new java.awt.Color(3, 33, 62));
        lblEmail1.setText("Nome de usuário");

        txtNome.setBackground(new java.awt.Color(241, 237, 237));
        txtNome.setForeground(new java.awt.Color(0, 0, 0));
        txtNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNome.setAlignmentX(1.0F);
        txtNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        }); 

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(3, 33, 62));
        jCheckBox1.setText("Mostrar senha");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(3, 33, 62));
        jLabel1.setText("Comida Favorita");

        txtComidaFavorita.setBackground(new java.awt.Color(241, 237, 237));
        txtComidaFavorita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtComidaFavorita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComidaFavoritaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadastre, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lblNome)
                        .addGap(138, 138, 138)
                        .addComponent(lblSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(bttnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblConfirmarSenha2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblConfirmarSenha3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtNomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSenha)
                                    .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pfConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtComidaFavorita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblConfirmarSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(checkBoxProfessor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkBoxAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCadastre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblSobrenome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmail1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(lblConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConfirmarSenha1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblConfirmarSenha3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConfirmarSenha2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(txtComidaFavorita, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxProfessor)
                    .addComponent(checkBoxAluno))
                .addGap(18, 18, 18)
                .addComponent(bttnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        final TelaCadastro tela = this;
        bttnCadastrar.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

				String nome = txtNome.getText();
				String sobrenome = txtSobrenome.getText();
				String user = txtNomeUser.getText();
				String email = txtEmail.getText();
				String senha = new String(pfSenha.getPassword());
				String confirmarSenha = new String(pfConfirmaSenha.getPassword()); 
				String teste_data = txtDataNasc.getText();
				String nomeCachorro = txtNomeCachorro.getText();
				boolean cargo_aluno = checkBoxAluno.isSelected();
				boolean cargo_prof = checkBoxProfessor.isSelected();
				String comidaFav = txtComidaFavorita.getText();

				new CadastroController().cadastrar(nome, sobrenome, email, user, senha, confirmarSenha, teste_data, nomeCachorro, cargo_aluno, cargo_prof, comidaFav, tela);
				
				// public void cadastrar(String nome, String sobrenome, String email, String
				// user, String senha, String confirmarSenha,
				// Date dataNasc, String nomeCachorro,boolean cargo_aluno) {

			}
		});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void txtSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void pfSenhaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void pfConfirmaSenhaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void checkBoxProfessorActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void checkBoxAlunoActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void bttnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void txtDataNascActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txtNomeCachorroActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void txtNomeUserActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	if(jCheckBox1.isSelected()) {
        	pfSenha.setEchoChar((char)0);
        	pfConfirmaSenha.setEchoChar((char)0);
        }else {
        	pfSenha.setEchoChar('\u2022');
        	pfConfirmaSenha.setEchoChar('\u2022');
        }
    }                                          

    private void txtComidaFavoritaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bttnCadastrar;
    private javax.swing.JCheckBox checkBoxAluno;
    private javax.swing.JCheckBox checkBoxProfessor;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCadastre;
    private javax.swing.JLabel lblConfirmarSenha;
    private javax.swing.JLabel lblConfirmarSenha1;
    private javax.swing.JLabel lblConfirmarSenha2;
    private javax.swing.JLabel lblConfirmarSenha3;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSobrenome;
    private javax.swing.JPasswordField pfConfirmaSenha;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField txtComidaFavorita;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeCachorro;
    private javax.swing.JTextField txtNomeUser;
    private javax.swing.JTextField txtSobrenome;
	
    public javax.swing.JTextField getTxtNome() {
		return txtNome;
	}

	public void setTxtNome(javax.swing.JTextField txtNome) {
		this.txtNome = txtNome;
	}

	public javax.swing.JPasswordField getPfConfirmaSenha() {
		return pfConfirmaSenha;
	}

	public void setPfConfirmaSenha(javax.swing.JPasswordField pfConfirmaSenha) {
		this.pfConfirmaSenha = pfConfirmaSenha;
	}

	public javax.swing.JPasswordField getPfSenha() {
		return pfSenha;
	}

	public void setPfSenha(javax.swing.JPasswordField pfSenha) {
		this.pfSenha = pfSenha;
	}

	public javax.swing.JTextField getTxtComidaFavorita() {
		return txtComidaFavorita;
	}

	public void setTxtComidaFavorita(javax.swing.JTextField txtComidaFavorita) {
		this.txtComidaFavorita = txtComidaFavorita;
	}

	public javax.swing.JTextField getTxtDataNasc() {
		return txtDataNasc;
	}

	public void setTxtDataNasc(javax.swing.JTextField txtDataNasc) {
		this.txtDataNasc = txtDataNasc;
	}

	public javax.swing.JTextField getTxtEmail() {
		return txtEmail;
	}

	public void setTxtEmail(javax.swing.JTextField txtEmail) {
		this.txtEmail = txtEmail;
	}

	public javax.swing.JTextField getTxtNomeCachorro() {
		return txtNomeCachorro;
	}

	public void setTxtNomeCachorro(javax.swing.JTextField txtNomeCachorro) {
		this.txtNomeCachorro = txtNomeCachorro;
	}

	public javax.swing.JTextField getTxtNomeUser() {
		return txtNomeUser;
	}

	public void setTxtNomeUser(javax.swing.JTextField txtNomeUser) {
		this.txtNomeUser = txtNomeUser;
	}

	public javax.swing.JTextField getTxtSobrenome() {
		return txtSobrenome;
	}

	public void setTxtSobrenome(javax.swing.JTextField txtSobrenome) {
		this.txtSobrenome = txtSobrenome;
	}
	
	
    
    // End of variables declaration                   
}
