package view;

import java.applet.Applet;
import java.applet.AudioClip;
import java.net.URL;

import model.dao.ProfessorDAO;
import model.vo.ProfessorVO;

public class TelaDeMenu extends javax.swing.JFrame {

	/**
	 * Creates new form TelaDeMenu
	 */
	public TelaDeMenu() {
		//SomFundo();
		initComponents();
		setExtendedState(MAXIMIZED_BOTH);
		 
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel5 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jPanel6 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jLabel8 = new javax.swing.JLabel();
		jButton7 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		JogosAnterioresjButton11 = new javax.swing.JButton();
		ConfiguracoesjButton19 = new javax.swing.JButton();
		jLabel11 = new javax.swing.JLabel();
		sairjButton20 = new javax.swing.JButton();
		LblNomeProfessor = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		LearnQuest = new javax.swing.JLabel();
		QuizjButton8 = new javax.swing.JButton();
		AcerteaPalavrajButton9 = new javax.swing.JButton();
		FormacaodeSilabasjLabel10 = new javax.swing.JButton();
		FlashCardjButton10 = new javax.swing.JButton();

		 
		
		jPanel5.setBackground(new java.awt.Color(3, 32, 62));

		//jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/image 1.png"))); // NOI18N
		jLabel2.setText("jLabel2");

		//jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 23.png"))); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		//jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Jogos anteriores (1).png"))); // NOI18N
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		//jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 29 (6).png"))); // NOI18N
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		//jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 10 (1).png"))); // NOI18N

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addGap(113, 113, 113).addComponent(jLabel3)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel4)
						.addContainerGap(84, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 208,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(jPanel5Layout.createSequentialGroup()
												.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 208,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(92, 92, 92)))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel5Layout.createSequentialGroup()
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(157, 157, 157))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel5Layout.createSequentialGroup().addComponent(jButton1).addGap(150, 150,
												150))))
				.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel5Layout.createSequentialGroup().addGap(0, 128, Short.MAX_VALUE)
								.addComponent(jLabel1).addGap(0, 283, Short.MAX_VALUE))));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addGap(64, 64, 64)
						.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(37, 37, 37)
						.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jButton4)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel5Layout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel3).addGap(146, 146, 146))
								.addGroup(jPanel5Layout.createSequentialGroup().addGap(87, 87, 87).addComponent(jLabel4)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119,
												Short.MAX_VALUE)))
						.addComponent(jButton1).addGap(67, 67, 67))
				.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel5Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jLabel1).addGap(0, 779, Short.MAX_VALUE))));

		jPanel6.setBackground(new java.awt.Color(3, 32, 62));

		//jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/image 1.png"))); // NOI18N
		jLabel6.setText("jLabel2");

		//jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 23.png"))); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		//jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Jogos anteriores (1).png"))); // NOI18N
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
//
		//jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 29 (6).png"))); // NOI18N
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});
		final TelaDeMenu tela = this;
		FormacaodeSilabasjLabel10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
			String autor = LblNomeProfessor.getText();
			CriarFormacaoDeSilabas tela1 = new CriarFormacaoDeSilabas(autor);
			tela1.setVisible(true);
			tela.dispose();
			}
		});

		//jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 10 (1).png"))); // NOI18N

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel6Layout.createSequentialGroup().addGap(113, 113, 113).addComponent(jLabel7)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel8)
						.addContainerGap(84, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 208,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(jPanel6Layout.createSequentialGroup()
												.addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 208,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(92, 92, 92)))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel6Layout.createSequentialGroup()
												.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(157, 157, 157))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel6Layout.createSequentialGroup().addComponent(jButton2).addGap(150, 150,
												150))))
				.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel6Layout.createSequentialGroup().addGap(0, 128, Short.MAX_VALUE)
								.addComponent(jLabel5).addGap(0, 283, Short.MAX_VALUE))));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel6Layout.createSequentialGroup().addGap(64, 64, 64)
						.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(37, 37, 37)
						.addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jButton6)
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel6Layout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel7).addGap(146, 146, 146))
								.addGroup(jPanel6Layout.createSequentialGroup().addGap(87, 87, 87).addComponent(jLabel8)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119,
												Short.MAX_VALUE)))
						.addComponent(jButton2).addGap(67, 67, 67))
				.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel6Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jLabel5).addGap(0, 779, Short.MAX_VALUE))));

		//jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Jogos anteriores (1).png"))); // NOI18N
		jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		//jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 29 (6).png"))); // NOI18N
		jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jButton12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton12ActionPerformed(evt);
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(3, 32, 62));
		jPanel1.setForeground(new java.awt.Color(3, 32, 62));
		jPanel1.setPreferredSize(new java.awt.Dimension(411, 786));

		//jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/image 1.png"))); // NOI18N
		jLabel9.setText("jLabel2");

		//JogosAnterioresjButton11
			//	.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Jogos anteriores (1).png"))); // NOI18N
		JogosAnterioresjButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		JogosAnterioresjButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				JogosAnterioresjButton11ActionPerformed(evt);
			}
		});

		//ConfiguracoesjButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 29 (6).png"))); // NOI18N
		ConfiguracoesjButton19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		ConfiguracoesjButton19.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ConfiguracoesjButton19ActionPerformed(evt);
			}
		});

		//jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 10 (1).png"))); // NOI18N

		//sairjButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 23.png"))); // NOI18N
		sairjButton20.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sairjButton20ActionPerformed(evt);
			}
		});

		LblNomeProfessor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		LblNomeProfessor.setForeground(new java.awt.Color(255, 255, 255));
		LblNomeProfessor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		LblNomeProfessor.setText("Nome do Professor");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(99, 99, 99).addGroup(jPanel1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addGap(98, 98, 98))
												.addComponent(ConfiguracoesjButton19,
														javax.swing.GroupLayout.PREFERRED_SIZE, 208,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout.createSequentialGroup().addComponent(
																		jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE,
																		69, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(167, 167, 167))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout.createSequentialGroup()
																		.addComponent(JogosAnterioresjButton11,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				208,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(98, 98, 98))))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addComponent(sairjButton20).addGap(155,
												155, 155))))
						.addComponent(LblNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 405,
								javax.swing.GroupLayout.PREFERRED_SIZE))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(70, 70, 70)
						.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(31, 31, 31).addComponent(LblNomeProfessor).addGap(29, 29, 29)
						.addComponent(JogosAnterioresjButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(ConfiguracoesjButton19).addGap(108, 108, 108)
						.addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(79, 79, 79).addComponent(sairjButton20).addGap(36, 36, 36)));

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));

		LearnQuest.setFont(new java.awt.Font("Segoe UI Black", 0, 60)); // NOI18N
		LearnQuest.setForeground(new java.awt.Color(3, 32, 62));
		LearnQuest.setText("Learn Quest");

		//QuizjButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 15 (1).png"))); // NOI18N
		QuizjButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				QuizjButton8ActionPerformed(evt);
			}
		});

		//AcerteaPalavrajButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 17 (2).png"))); // NOI18N
		AcerteaPalavrajButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AcerteaPalavrajButton9ActionPerformed(evt);
			}
		});

		///FormacaodeSilabasjLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 16.png"))); // NOI18N

		//FlashCardjButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 20 (1).png"))); // NOI18N
		FlashCardjButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				FlashCardjButton10ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(84, 84, 84).addComponent(LearnQuest))
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(39, 39, 39)
								.addComponent(QuizjButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 251,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(AcerteaPalavrajButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 251,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(15, 15, 15)
								.addComponent(FormacaodeSilabasjLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 253,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(FlashCardjButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 246,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(45, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(44, 44, 44).addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(jPanel2Layout.createSequentialGroup().addComponent(LearnQuest).addGroup(jPanel2Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(123, 123, 123).addComponent(
										QuizjButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 389,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel2Layout.createSequentialGroup()
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(AcerteaPalavrajButton9,
														javax.swing.GroupLayout.PREFERRED_SIZE, 389,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addComponent(FormacaodeSilabasjLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 389,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(FlashCardjButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 389,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0).addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void QuizjButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		String autor = LblNomeProfessor.getText();
		CriarQuiz telaQuiz = new CriarQuiz(autor);
		telaQuiz.setVisible(true);
		tela1.dispose();
	}

	private void AcerteaPalavrajButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		 new CriarAcerteAPalavra(LblNomeProfessor.getText()).setVisible(true);
		 tela1.dispose();
	}

	private void FlashCardjButton10ActionPerformed(java.awt.event.ActionEvent evt) {
		new CriarFlashCar(LblNomeProfessor.getText()).setVisible(true);
		tela1.dispose();
	}
	final TelaDeMenu tela1 = this;
	private void JogosAnterioresjButton11ActionPerformed(java.awt.event.ActionEvent evt) {
		String autor = LblNomeProfessor.getText();
		AlterarQuestao tela = new AlterarQuestao(autor);
		tela.setVisible(true);
		tela1.dispose();
	}

	private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	} 

	private void ConfiguracoesjButton19ActionPerformed(java.awt.event.ActionEvent evt) {
		String nome = LblNomeProfessor.getText();
		int idProfessor = new ProfessorDAO().pegarIdComNomeUser(nome);
		ProfessorVO professor= new ProfessorDAO().pegarDadosProfessorComId(idProfessor);
		AlterarDados tela = new AlterarDados();
		tela.getjLabel4().setText("Nome Completo: "+professor.getNome() + " "+professor.getSobrenome());
		tela.getjLabel5().setText("Nome de Usuário: "+professor.getUser());
		tela.getjLabel7().setText("Email: "+professor.getEmail());
		tela.setVisible(true);
		  
	}

	private void sairjButton20ActionPerformed(java.awt.event.ActionEvent evt) {
		TelaLogin tela = new TelaLogin();
		tela.setVisible(true);
		tela1.dispose();
	}
	
	/*private void SomFundo() {
		URL url = getClass().getResource("/audios/teste2.wav");
		AudioClip audio = Applet.newAudioClip(url);
		audio.loop();
		 
	}*/

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaDeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaDeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaDeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaDeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaDeMenu().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton AcerteaPalavrajButton9;
	private javax.swing.JButton ConfiguracoesjButton19;
	private javax.swing.JButton FlashCardjButton10;
	private javax.swing.JButton FormacaodeSilabasjLabel10;
	private javax.swing.JButton JogosAnterioresjButton11;
	private javax.swing.JLabel LblNomeProfessor;
	private javax.swing.JLabel LearnQuest;
	private javax.swing.JButton QuizjButton8;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JButton sairjButton20;
	// End of variables declaration
	public javax.swing.JLabel getLblNomeProfessor() {
		return LblNomeProfessor;
	}

	public void setLblNomeProfessor(javax.swing.JLabel lblNomeProfessor) {
		this.LblNomeProfessor = lblNomeProfessor;
	}
}
