package view;

import javax.swing.JOptionPane; 

import controller.QuizController;
import model.dao.QuizQuestaoDAO;
import model.dao.QuizDAO;

public class TelaQuiz extends javax.swing.JFrame {
	public int numeroQuestaoAtual = 1;

	/**
	 * Creates new form TelaQuiz
	 * @param id_jogo 
	 */
	String id_jogo = null;
	public TelaQuiz(String id_jogo) {
		initComponents();
		setExtendedState(MAXIMIZED_BOTH);
		this.id_jogo = id_jogo;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jSplitPane1 = new javax.swing.JSplitPane();
		jRadioButton1 = new javax.swing.JRadioButton();
		buttonGroup1 = new javax.swing.ButtonGroup();
		buttonGroup2 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		lblNumeroQuestao = new javax.swing.JLabel();
		QuebraCabecajLabel2 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		QuebraCabecajLabel5 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		txtPergunta = new javax.swing.JEditorPane();
		Alternativa1jCheckBox = new javax.swing.JCheckBox();
		Alternativa2jCheckBox2 = new javax.swing.JCheckBox();
		Alternativa3jCheckBox3 = new javax.swing.JCheckBox();
		Alternativa4JCheckBox = new javax.swing.JCheckBox();
		bttnFinalizarQuiz = new javax.swing.JButton();
		LabelVazia = new javax.swing.JLabel();
		txtAlternativaA = new javax.swing.JTextField();
		txtAlternativaB = new javax.swing.JTextField();
		txtAlternativaC = new javax.swing.JTextField();
		txtAlternativaD = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabelTituloDoQuiz1 = new javax.swing.JLabel();
		bttnPróximaQuestao = new javax.swing.JButton();

		jRadioButton1.setText("jRadioButton1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		lblNumeroQuestao.setFont(new java.awt.Font("Segoe UI Black", 0, 60)); // NOI18N
		lblNumeroQuestao.setForeground(new java.awt.Color(107, 131, 125));
		lblNumeroQuestao.setText("1");

		QuebraCabecajLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 26.png"))); // NOI18N

		QuebraCabecajLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 27.png"))); // NOI18N
		QuebraCabecajLabel5.setText("jLabel5");

		txtPergunta.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
		jScrollPane2.setViewportView(txtPergunta);

		Alternativa1jCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		Alternativa1jCheckBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Alternativa1jCheckBoxActionPerformed(evt);
			}
		});

		Alternativa2jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		Alternativa2jCheckBox2.setToolTipText("");
		Alternativa2jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Alternativa2jCheckBox2ActionPerformed(evt);
			}
		});

		Alternativa3jCheckBox3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		Alternativa3jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Alternativa3jCheckBox3ActionPerformed(evt);
			}
		});

		Alternativa4JCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		Alternativa4JCheckBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Alternativa4JCheckBoxActionPerformed(evt);
			}
		});

		bttnFinalizarQuiz.setBackground(new java.awt.Color(107, 131, 125));
		bttnFinalizarQuiz.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
		bttnFinalizarQuiz.setForeground(new java.awt.Color(255, 255, 255));
		bttnFinalizarQuiz.setText("Finalizar Quiz");
		bttnFinalizarQuiz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		bttnFinalizarQuiz.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bttnFinalizarQuizActionPerformed(evt);
			}
		});

		txtAlternativaA.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
		txtAlternativaA.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtAlternativaAActionPerformed(evt);
			}
		});
		
		txtAlternativaB.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
		txtAlternativaC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
		txtAlternativaD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

		jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(105, 129, 122));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("A");

		jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(105, 129, 122));
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText("B");

		jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(105, 129, 122));
		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setText("C");

		jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(105, 129, 122));
		jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel5.setText("D");

		jLabelTituloDoQuiz1.setFont(new java.awt.Font("Segoe UI Black", 0, 60)); // NOI18N
		jLabelTituloDoQuiz1.setForeground(new java.awt.Color(107, 131, 125));
		jLabelTituloDoQuiz1.setText("Quiz - questão");

		bttnPróximaQuestao.setBackground(new java.awt.Color(107, 131, 125));
		bttnPróximaQuestao.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
		bttnPróximaQuestao.setForeground(new java.awt.Color(255, 255, 255));
		bttnPróximaQuestao.setText("Próxima questão");
		bttnPróximaQuestao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		bttnPróximaQuestao.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bttnPróximaQuestaoActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(35, 35, 35).addComponent(QuebraCabecajLabel2)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(535, 535, 535)
										.addComponent(lblNumeroQuestao))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(71, 71, 71)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														jPanel1Layout.createSequentialGroup()
																.addComponent(bttnPróximaQuestao,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 161,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18, 18).addComponent(bttnFinalizarQuiz,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 161,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel1Layout.createSequentialGroup().addGap(576, 576, 576)
														.addComponent(LabelVazia))
												.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
														1107, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addComponent(jLabel3,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 37,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(Alternativa3jCheckBox3))
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addComponent(jLabel5,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 37,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(Alternativa4JCheckBox))
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addComponent(jLabel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 37,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(Alternativa1jCheckBox))
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addComponent(jLabel2,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 37,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(Alternativa2jCheckBox2)))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addComponent(txtAlternativaD)
																.addComponent(txtAlternativaC)
																.addComponent(txtAlternativaB)
																.addComponent(txtAlternativaA,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 1039,
																		Short.MAX_VALUE))))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
						.addComponent(QuebraCabecajLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(415, 415, 415).addComponent(jLabel4).addGap(153, 153, 153))
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(234, 234, 234)
								.addComponent(jLabelTituloDoQuiz1).addContainerGap(1372, Short.MAX_VALUE))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addComponent(QuebraCabecajLabel2).addGap(0, 0,
						Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(QuebraCabecajLabel5)
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(54, 54, 54)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel4).addComponent(LabelVazia))
												.addGap(15, 15, 15)
												.addComponent(lblNumeroQuestao, javax.swing.GroupLayout.PREFERRED_SIZE,
														74, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(26, 26, 26).addComponent(jScrollPane2,
														javax.swing.GroupLayout.PREFERRED_SIZE, 114,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(51, 51, 51)
												.addComponent(Alternativa1jCheckBox))
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(40, 40, 40)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(txtAlternativaA,
																javax.swing.GroupLayout.DEFAULT_SIZE, 40,
																Short.MAX_VALUE))))
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(53, 53, 53)
												.addComponent(Alternativa2jCheckBox2))
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(41, 41, 41)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(txtAlternativaB,
																javax.swing.GroupLayout.DEFAULT_SIZE, 40,
																Short.MAX_VALUE)
														.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55,
										Short.MAX_VALUE)
								.addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(txtAlternativaC, javax.swing.GroupLayout.DEFAULT_SIZE, 40,
												Short.MAX_VALUE)
										.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												jPanel1Layout.createSequentialGroup()
														.addComponent(Alternativa3jCheckBox3).addGap(9, 9, 9)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14,
										Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(43, 43,
												43).addComponent(Alternativa4JCheckBox).addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
												.createSequentialGroup().addGap(18, 30, Short.MAX_VALUE)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(txtAlternativaD,
																javax.swing.GroupLayout.DEFAULT_SIZE, 40,
																Short.MAX_VALUE))
												.addGap(58, 58, 58)))
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(bttnFinalizarQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(bttnPróximaQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(106, 106, 106))
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(64, 64, 64)
								.addComponent(jLabelTituloDoQuiz1).addContainerGap(693, Short.MAX_VALUE))));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(jPanel1,
						javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>

	private void Alternativa1jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code hee:
		if (Alternativa1jCheckBox.isSelected()) {
			Alternativa2jCheckBox2.setSelected(false);
			Alternativa3jCheckBox3.setSelected(false);
			Alternativa4JCheckBox.setSelected(false);
		}
	}

	private void Alternativa2jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (Alternativa2jCheckBox2.isSelected()) {
			Alternativa1jCheckBox.setSelected(false);
			Alternativa3jCheckBox3.setSelected(false);
			Alternativa4JCheckBox.setSelected(false);
		}
	}

	private void Alternativa3jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (Alternativa3jCheckBox3.isSelected()) {
			Alternativa1jCheckBox.setSelected(false);
			Alternativa2jCheckBox2.setSelected(false);
			Alternativa4JCheckBox.setSelected(false);
		}
	}

	final TelaQuiz tela1 = this;

	private void bttnFinalizarQuizActionPerformed(java.awt.event.ActionEvent evt) {
		TelaDeMenu tela = new TelaDeMenu();
		String idUltimoQuiz = new QuizDAO().pegarUltimoIdQuiz();
		JOptionPane.showMessageDialog(null, "Quiz Finalizado, codigo do quiz: " + idUltimoQuiz);
		tela.setVisible(true);
		tela1.dispose();
	}

	private void txtAlternativaAActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	final TelaQuiz tela = this;

	private void bttnPróximaQuestaoActionPerformed(java.awt.event.ActionEvent evt) {
		String questao = txtPergunta.getText();
		String alternativa1 = txtAlternativaA.getText();
		String alternativa2 = txtAlternativaB.getText();
		String alternativa3 = txtAlternativaC.getText();
		String alternativa4 = txtAlternativaD.getText();
		String resposta = null;
		if (Alternativa1jCheckBox.isSelected()) {
			resposta = alternativa1;
		}
		if (Alternativa2jCheckBox2.isSelected()) {
			resposta = alternativa2;
		}
		if (Alternativa3jCheckBox3.isSelected()) {
			resposta = alternativa3;
		}
		if (Alternativa4JCheckBox.isSelected()) {
			resposta = alternativa1;
		}
		int i = new QuizQuestaoDAO().pegarUltimoIdQuestao();
		i++;
		
		
		new QuizController().adcionarQuestao(questao, alternativa1, alternativa2, alternativa3, alternativa4, resposta,
				tela, id_jogo );

	}

	private void Alternativa4JCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (Alternativa4JCheckBox.isSelected()) {
			Alternativa1jCheckBox.setSelected(false);
			Alternativa2jCheckBox2.setSelected(false);
			Alternativa3jCheckBox3.setSelected(false);
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaQuiz(null).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JCheckBox Alternativa1jCheckBox;

	public javax.swing.JCheckBox getAlternativa1jCheckBox() {
		return Alternativa1jCheckBox;
	}

	public void setAlternativa1jCheckBox(javax.swing.JCheckBox alternativa1jCheckBox) {
		Alternativa1jCheckBox = alternativa1jCheckBox;
	}

	public javax.swing.JCheckBox getAlternativa2jCheckBox2() {
		return Alternativa2jCheckBox2;
	}

	public void setAlternativa2jCheckBox2(javax.swing.JCheckBox alternativa2jCheckBox2) {
		Alternativa2jCheckBox2 = alternativa2jCheckBox2;
	}

	public javax.swing.JCheckBox getAlternativa3jCheckBox3() {
		return Alternativa3jCheckBox3;
	}

	public void setAlternativa3jCheckBox3(javax.swing.JCheckBox alternativa3jCheckBox3) {
		Alternativa3jCheckBox3 = alternativa3jCheckBox3;
	}

	public javax.swing.JCheckBox getAlternativa4JCheckBox() {
		return Alternativa4JCheckBox;
	}

	public void setAlternativa4JCheckBox(javax.swing.JCheckBox alternativa4jCheckBox) {
		Alternativa4JCheckBox = alternativa4jCheckBox;
	}

	public javax.swing.JTextField getTxtAlternativaA() {
		return txtAlternativaA;
	}

	public void setTxtAlternativaA(javax.swing.JTextField txtAlternativaA) {
		this.txtAlternativaA = txtAlternativaA;
	}

	public javax.swing.JTextField getTxtAlternativaB() {
		return txtAlternativaB;
	}

	public void setTxtAlternativaB(javax.swing.JTextField txtAlternativaB) {
		this.txtAlternativaB = txtAlternativaB;
	}

	public javax.swing.JTextField getTxtAlternativaC() {
		return txtAlternativaC;
	}

	public void setTxtAlternativaC(javax.swing.JTextField txtAlternativaC) {
		this.txtAlternativaC = txtAlternativaC;
	}

	public javax.swing.JTextField getTxtAlternativaD() {
		return txtAlternativaD;
	}

	public void setTxtAlternativaD(javax.swing.JTextField txtAlternativaD) {
		this.txtAlternativaD = txtAlternativaD;
	}

	public javax.swing.JEditorPane getTxtPergunta() {
		return txtPergunta;
	}

	public void setTxtPergunta(javax.swing.JEditorPane txtPergunta) {
		this.txtPergunta = txtPergunta;
	}

	private javax.swing.JCheckBox Alternativa2jCheckBox2;
	private javax.swing.JCheckBox Alternativa3jCheckBox3;
	private javax.swing.JCheckBox Alternativa4JCheckBox;
	private javax.swing.JLabel LabelVazia;
	private javax.swing.JLabel QuebraCabecajLabel2;
	private javax.swing.JLabel QuebraCabecajLabel5;
	private javax.swing.JButton bttnFinalizarQuiz;
	private javax.swing.JButton bttnPróximaQuestao;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.ButtonGroup buttonGroup2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabelTituloDoQuiz1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JSplitPane jSplitPane1;
	public javax.swing.JLabel lblNumeroQuestao;
	private javax.swing.JTextField txtAlternativaA;
	private javax.swing.JTextField txtAlternativaB;
	private javax.swing.JTextField txtAlternativaC;
	private javax.swing.JTextField txtAlternativaD;
	private javax.swing.JEditorPane txtPergunta;
	// End of variables declaration

}
