 package view;

import java.sql.Timestamp; 

import controller.QuizQuestaoController;
import model.dao.QuizDAO;

public class TelaQuizAluno extends javax.swing.JFrame {

	int numeroQuestao = 0;
	int acertos = 0 ;
	Timestamp tempoInicial;
	/**
	 * Creates new form TelaQuiz
	 */
	public TelaQuizAluno(Timestamp tempoInicial) {
		initComponents();
		setExtendedState(MAXIMIZED_BOTH);
		this.tempoInicial = tempoInicial;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jSplitPane1 = new javax.swing.JSplitPane();
		jRadioButton1 = new javax.swing.JRadioButton();
		buttonGroup1 = new javax.swing.ButtonGroup();
		buttonGroup2 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		QuebraCabecajLabel2 = new javax.swing.JLabel();
		QuestaoAlunojLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		QuebracabecajLabel5 = new javax.swing.JLabel();
		Alternativa1jCheckBox1 = new javax.swing.JCheckBox();
		Alternativa2jCheckBox2 = new javax.swing.JCheckBox();
		Alternativa3jCheckBox3 = new javax.swing.JCheckBox();
		Alternativa4jCheckBox4 = new javax.swing.JCheckBox();
		ContinuarjButton1 = new javax.swing.JButton();
		NomeDoQuizjLabel6 = new javax.swing.JLabel();
		NomeDoAlunojLabel7 = new javax.swing.JLabel();
		TotalDeTempojLabel8 = new javax.swing.JLabel();
		TotaldeQuestoesjLabel9 = new javax.swing.JLabel();
		TempoGastojLabel10 = new javax.swing.JLabel();

		jRadioButton1.setText("jRadioButton1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 60)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(107, 131, 125));
		jLabel1.setText("Quiz");

		QuebraCabecajLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 26.png"))); // NOI18N

		QuestaoAlunojLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		QuestaoAlunojLabel3.setText("Questão 1 - (Informe)");

		QuebracabecajLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Group 27.png"))); // NOI18N
		QuebracabecajLabel5.setText("jLabel5");

		Alternativa1jCheckBox1.setText("Alternativa 1");
		Alternativa1jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				if (Alternativa1jCheckBox1.isSelected()) {
					Alternativa2jCheckBox2.setSelected(false);
					Alternativa3jCheckBox3.setSelected(false);
					Alternativa4jCheckBox4.setSelected(false);
				}
			}
		});

		Alternativa2jCheckBox2.setText("Alternativa 2");
		Alternativa2jCheckBox2.setToolTipText("");
		Alternativa2jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				if (Alternativa2jCheckBox2.isSelected()) {
					Alternativa1jCheckBox1.setSelected(false);
					Alternativa3jCheckBox3.setSelected(false);
					Alternativa4jCheckBox4.setSelected(false);
				}
			}
		});

		Alternativa3jCheckBox3.setText("Alternativa 3");
		Alternativa3jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				if (Alternativa3jCheckBox3.isSelected()) {
					Alternativa1jCheckBox1.setSelected(false);
					Alternativa2jCheckBox2.setSelected(false);
					Alternativa4jCheckBox4.setSelected(false);
				}
			}
		});

		Alternativa4jCheckBox4.setText("Alternativa 4");
		Alternativa4jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				if (Alternativa4jCheckBox4.isSelected()) {
					Alternativa1jCheckBox1.setSelected(false);
					Alternativa2jCheckBox2.setSelected(false);
					Alternativa3jCheckBox3.setSelected(false);
				}
			}
		});
		final TelaQuizAluno tela = this;
		ContinuarjButton1.setText("Continuar");
		ContinuarjButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		ContinuarjButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				numeroQuestao++;
				String resposta = null;
				if (Alternativa1jCheckBox1.isSelected()) {
					resposta = Alternativa1jCheckBox1.getText();
				}
				if (Alternativa2jCheckBox2.isSelected()) {
					resposta = Alternativa2jCheckBox2.getText();
				}
				if (Alternativa3jCheckBox3.isSelected()) {
					resposta = Alternativa3jCheckBox3.getText();
				}
				if (Alternativa4jCheckBox4.isSelected()) {
					resposta = Alternativa4jCheckBox4.getText();
				}

				
				
				String id_quiz = NomeDoQuizjLabel6.getText();
				QuizQuestaoController QuizQuestaoController = new QuizQuestaoController();
				boolean acertou = QuizQuestaoController.verificarResposta(resposta, id_quiz, acertos, numeroQuestao);
				if(acertou) {
					acertos++;
				}
				
				 
				new QuizQuestaoController().visualizarQuestoesBotaoContinuar(id_quiz, numeroQuestao, tela, acertos, tempoInicial);
				
				
			}
		});

		NomeDoQuizjLabel6.setText("(nome do quiz)");

		NomeDoAlunojLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		NomeDoAlunojLabel7.setText("Nome do aluno:");

		TotalDeTempojLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		TotalDeTempojLabel8.setText("Total de tempo:");

		TotaldeQuestoesjLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		TotaldeQuestoesjLabel9.setText("Total de questões:");

		TempoGastojLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		TempoGastojLabel10.setText("Tempo gasto:");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(QuebraCabecajLabel2)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(42, 42, 42).addComponent(jLabel1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(NomeDoQuizjLabel6))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(56, 56, 56)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(TotaldeQuestoesjLabel9).addComponent(NomeDoAlunojLabel7)
												.addComponent(TotalDeTempojLabel8).addComponent(TempoGastojLabel10))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(Alternativa1jCheckBox1).addComponent(Alternativa2jCheckBox2)
										.addComponent(Alternativa3jCheckBox3).addComponent(Alternativa4jCheckBox4))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(QuestaoAlunojLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 584,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116,
												Short.MAX_VALUE)
										.addComponent(QuebracabecajLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(48, 48, 48)))
						.addComponent(jLabel4).addGap(153, 153, 153))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(ContinuarjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(406, 406, 406)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel4))
								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(QuestaoAlunojLabel3,
														javax.swing.GroupLayout.PREFERRED_SIZE, 107,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1).addComponent(NomeDoQuizjLabel6))
										.addComponent(QuebracabecajLabel5))
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout.createSequentialGroup().addGap(40, 40, 40)
														.addComponent(NomeDoAlunojLabel7)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(TotaldeQuestoesjLabel9).addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3,
																Short.MAX_VALUE))
												.addGroup(jPanel1Layout.createSequentialGroup().addGap(57, 57, 57)
														.addComponent(Alternativa1jCheckBox1)
														.addGap(0, 0, Short.MAX_VALUE)))))
						.addGap(58, 58, 58).addComponent(Alternativa2jCheckBox2).addGap(40, 40, 40)
						.addComponent(TotalDeTempojLabel8)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(TempoGastojLabel10).addComponent(Alternativa3jCheckBox3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
						.addComponent(Alternativa4jCheckBox4).addGap(103, 103, 103)
						.addComponent(ContinuarjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(66, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup().addComponent(QuebraCabecajLabel2)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 12, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	public javax.swing.JLabel getQuestaoAlunojLabel3() {
		return QuestaoAlunojLabel3;
	}

	public void setQuestaoAlunojLabel3(javax.swing.JLabel questaoAlunojLabel3) {
		QuestaoAlunojLabel3 = questaoAlunojLabel3;
	}

	public javax.swing.JCheckBox getAlternativa1jCheckBox1() {
		return Alternativa1jCheckBox1;
	}

	public void setAlternativa1jCheckBox1(javax.swing.JCheckBox alternativa1jCheckBox1) {
		Alternativa1jCheckBox1 = alternativa1jCheckBox1;
	}

	public javax.swing.JCheckBox getAlternativa2jCheckBox2() {
		return Alternativa2jCheckBox2;
	}

	public void setAlternativa2jCheckBox2(javax.swing.JCheckBox alternativa2jCheckBox2) {
		Alternativa2jCheckBox2 = alternativa2jCheckBox2;
	}

	public javax.swing.JCheckBox getAlternativa3jCheckBox3() {
		return Alternativa3jCheckBox3;
	}

	public void setAlternativa3jCheckBox3(javax.swing.JCheckBox alternativa3jCheckBox3) {
		Alternativa3jCheckBox3 = alternativa3jCheckBox3;
	}

	public javax.swing.JCheckBox getAlternativa4jCheckBox4() {
		return Alternativa4jCheckBox4;
	}

	public void setAlternativa4jCheckBox4(javax.swing.JCheckBox alternativa4jCheckBox4) {
		Alternativa4jCheckBox4 = alternativa4jCheckBox4;
	}

	private void Alternativa3jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void Alternativa2jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void Alternativa1jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void ContinuarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void Alternativa4jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaQuizAluno.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaQuizAluno.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaQuizAluno.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaQuizAluno.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaQuizAluno(null).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JCheckBox Alternativa1jCheckBox1;
	private javax.swing.JCheckBox Alternativa2jCheckBox2;
	private javax.swing.JCheckBox Alternativa3jCheckBox3;
	private javax.swing.JCheckBox Alternativa4jCheckBox4;
	private javax.swing.JButton ContinuarjButton1;
	private javax.swing.JLabel NomeDoAlunojLabel7;
	private javax.swing.JLabel NomeDoQuizjLabel6;
	private javax.swing.JLabel QuebraCabecajLabel2;
	private javax.swing.JLabel QuebracabecajLabel5;
	private javax.swing.JLabel QuestaoAlunojLabel3;
	private javax.swing.JLabel TempoGastojLabel10;
	private javax.swing.JLabel TotalDeTempojLabel8;
	private javax.swing.JLabel TotaldeQuestoesjLabel9;
	private javax.swing.ButtonGroup buttonGroup1; 
	private javax.swing.ButtonGroup buttonGroup2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JSplitPane jSplitPane1;
	// End of variables declaration
	
	public javax.swing.JLabel getNomeDoAlunojLabel7() {
		return NomeDoAlunojLabel7;
	}

	public void setNomeDoAlunojLabel7(javax.swing.JLabel nomeDoAlunojLabel7) {
		NomeDoAlunojLabel7 = nomeDoAlunojLabel7;
	}

	public javax.swing.JLabel getNomeDoQuizjLabel6() {
		return NomeDoQuizjLabel6;
	}

	public void setNomeDoQuizjLabel6(javax.swing.JLabel nomeDoQuizjLabel6) {
		NomeDoQuizjLabel6 = nomeDoQuizjLabel6;
	}

	public javax.swing.JLabel getTotalDeTempojLabel8() {
		return TotalDeTempojLabel8;
	}

	public void setTotalDeTempojLabel8(javax.swing.JLabel totalDeTempojLabel8) {
		TotalDeTempojLabel8 = totalDeTempojLabel8;
	}

	public javax.swing.JLabel getTotaldeQuestoesjLabel9() {
		return TotaldeQuestoesjLabel9;
	}

	public void setTotaldeQuestoesjLabel9(javax.swing.JLabel totaldeQuestoesjLabel9) {
		TotaldeQuestoesjLabel9 = totaldeQuestoesjLabel9;
	}

	public javax.swing.JButton getContinuarjButton1() {
		return ContinuarjButton1;
	}

	public void setContinuarjButton1(javax.swing.JButton continuarjButton1) {
		ContinuarjButton1 = continuarjButton1;
	}

	
	

	
}
